//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pangea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud_Cambio_Turno
    {
        public int id { get; set; }
        public int id_turno { get; set; }
        public string estado { get; set; }
        public int id_trabajador_crea { get; set; }
        public int id_trabajador_eval { get; set; }
        public System.DateTime fecha_crea { get; set; }
        public System.DateTime fecha_eval { get; set; }
        public System.DateTime fecha_nueva { get; set; }
        public int id_tipo_turno_nuevo { get; set; }
        public string observacion { get; set; }
    
        public virtual Turno Turno { get; set; }
    }
}
