//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pangea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrabajadorDestino
    {
        public int id { get; set; }
        public int id_destino { get; set; }
        public int id_trabajador { get; set; }
        public int id_actividad { get; set; }
        public bool habilitado { get; set; }
    
        public virtual Actividad Actividad { get; set; }
        public virtual Destino Destino { get; set; }
        public virtual Trabajador Trabajador { get; set; }
    }
}
