//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pangea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Turno()
        {
            this.Presencia = new HashSet<Presencia>();
            this.Solicitud_Cambio_Turno = new HashSet<Solicitud_Cambio_Turno>();
        }
    
        public int id { get; set; }
        public int id_tipo_turno { get; set; }
        public System.DateTime fecha { get; set; }
        public int id_sucursal { get; set; }
        public string estado { get; set; }
        public int id_trabajador_asignado { get; set; }
        public int id_trabajador_crea { get; set; }
        public System.DateTime fecha_crea { get; set; }
        public int id_trabajador_modif { get; set; }
        public System.DateTime fecha_modif { get; set; }
        public int id_trabajador_elimina { get; set; }
        public System.DateTime fecha_elimina { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Presencia> Presencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Cambio_Turno> Solicitud_Cambio_Turno { get; set; }
        public virtual Tipo_Turno Tipo_Turno { get; set; }
        public virtual Trabajador Trabajador { get; set; }
    }
}
